### Get all runs
GET http://localhost:8080/runs

### Create a new run
POST http://localhost:8080/runs
Content-Type: application/json

{
  "date": "2025-09-28",
  "distance": 19,
  "duration": 67
}

### Get specific run we just created
GET http://localhost:8080/runs/1

### Modify existing run
PUT http://localhost:8080/runs/4
Content-Type: application/json

{
  "date": "2025-09-28",
  "distance": 67.0,
  "duration": 159
}

### Get specific run we just created
GET http://localhost:8080/runs/1

### Delete the run we made and modified
DELETE http://localhost:8080/runs/2

### Get all runs
GET http://localhost:8080/runs



